[fix #22] router 명칭 변경
Think-Tank-6/VOS-server pull request #25
Opened 2024-01-02 09:21 UTC by neymaru

## 📌 작업 이슈
closed #22 

## 📄 작업 내용
- router 및 파일명 auth -> user로 변경
- router prefix 변경
- AuthRepository -> UserRepository 클래스명 변경

## 🌟 요청 사항

2024-01-02 09:22 UTC, KyhNaz approved these changes

2024-01-02 09:25 UTC, 2dilution2 approved these changes

2024-01-02 09:28 UTC, 2dilution2 requested changes
user_repo 변경 부탁드립니다

2024-01-03 07:13 UTC, Somang-Kang approved these changes

2024-01-03 07:14 UTC, 2dilution2 approved these changes

2024-01-03 07:14 UTC, merged